// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearLogs() {
  return window['go']['main']['App']['ClearLogs']();
}

export function DiscoverPorts() {
  return window['go']['main']['App']['DiscoverPorts']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetLogs() {
  return window['go']['main']['App']['GetLogs']();
}

export function GetRuntimeState() {
  return window['go']['main']['App']['GetRuntimeState']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function StartFrpc() {
  return window['go']['main']['App']['StartFrpc']();
}

export function StopFrpc() {
  return window['go']['main']['App']['StopFrpc']();
}
