// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ClearLogs():Promise<void>;

export function DiscoverPorts():Promise<Array<number>>;

export function GetConfig():Promise<main.AppConfig>;

export function GetLogs():Promise<Array<string>>;

export function GetRuntimeState():Promise<main.RuntimeState>;

export function SaveConfig(arg1:main.AppConfig):Promise<void>;

export function StartFrpc():Promise<void>;

export function StopFrpc():Promise<void>;
